apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciyex-portal-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ciyex-portal-ui
          image: registry.apps-prod.us-east.in.hinisoft.com/ciyex-portal-ui:2.0.2
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.ciyex.org"
            - name: NEXT_PUBLIC_KEYCLOAK_ENABLED
              value: "true"
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              value: "https://aran.me"
            - name: NEXT_PUBLIC_KEYCLOAK_REALM
              value: "master"
            - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
              value: "ciyex-app"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
