apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ciyex-prod

resources:
  - ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: prod
    includeSelectors: false

replicas:
  - name: ciyex-portal-ui
    count: 1

images:
  - name: registry.apps-prod.us-east.in.hinisoft.com/ciyex-portal-ui
    newTag: "0.0.1-alpha.8"

configMapGenerator:
  - name: portal-ui-config
    literals:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.ciyex.org

patches:
  - target:
      kind: Deployment
      name: ciyex-portal-ui
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0
        value:
          configMapRef:
            name: portal-ui-config
  - target:
      kind: Ingress
      name: ciyex-portal-ui-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: ciyex-portal.apps-prod.in.hinisoft.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ciyex-portal.apps-prod.in.hinisoft.com
