apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciyex-portal-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ciyex-portal-ui
          image: registry.apps-prod.us-east.in.hinisoft.com/ciyex-portal-ui:0.0.1-alpha.20
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_ENV
              value: "dev"
            - name: NEXT_PUBLIC_API_URL
              value: "https://ciyex-api.apps-dev.in.hinisoft.com"
            - name: NEXT_PUBLIC_KEYCLOAK_ENABLED
              value: "true"
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              value: "https://aran.apps-dev.in.hinisoft.com"
            - name: NEXT_PUBLIC_KEYCLOAK_REALM
              value: "master"
            - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
              value: "ciyex-app"
