apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ciyex-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: dev
    includeSelectors: false

replicas:
  - name: ciyex-portal-ui
    count: 1

images:
  - name: registry.apps-prod.us-east.in.hinisoft.com/ciyex-portal-ui
    newTag: "2.0.2-alpha.11"

patches:
  - target:
      kind: Ingress
      name: ciyex-portal-ui-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: ciyex-portal.apps-dev.in.hinisoft.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ciyex-portal.apps-dev.in.hinisoft.com

configMapGenerator:
  - name: portal-ui-config
    literals:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://ciyex-api.apps-dev.in.hinisoft.com
