apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ciyex-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: dev
    includeSelectors: false

replicas:
  - name: ciyex-portal-ui
    count: 1

images:
  - name: registry.apps-prod.us-east.in.hinisoft.com/ciyex-portal-ui
    newTag: "0.0.1-alpha.9"

configMapGenerator:
  - name: portal-ui-config
    literals:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://api-dev.ciyex.org
      - NEXT_PUBLIC_KEYCLOAK_URL=https://dev.aran.me
      - NEXT_PUBLIC_KEYCLOAK_REALM=master
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=ciyex-app
      - NEXT_PUBLIC_KEYCLOAK_ENABLED=true

patches:
  - target:
      kind: Deployment
      name: ciyex-portal-ui
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0
        value:
          configMapRef:
            name: portal-ui-config
      - op: remove
        path: /spec/template/spec/containers/0/startupProbe
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
        value: /
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
        value: /
  - target:
      kind: Ingress
      name: ciyex-portal-ui-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: portal-dev.ciyex.org
      - op: replace
        path: /spec/tls/0/hosts/0
        value: portal-dev.ciyex.org
